### ISSUE TITLE
[feature suggestion] Windows optimizations (segmented heap)

### ISSUE THREAD

**Issue by ghost** [ggml-org/whisper.cpp#191]
I've locally patched up recent binaries with this manifest  

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> 
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0"> 
  <application xmlns="urn:schemas-microsoft-com:asm.v3"> 
     <windowsSettings> <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>                   </windowsSettings> 
     <windowsSettings> <heapType      xmlns="http://schemas.microsoft.com/SMI/2020/WindowsSettings">SegmentHeap</heapType>                 </windowsSettings> 
  </application> 
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"> 
    <security> 
      <requestedPrivileges> 
        <requestedExecutionLevel level="asInvoker" uiAccess="false" /> 
      </requestedPrivileges> 
    </security> 
  </trustInfo> 
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
    <application> 
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" /> 
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}" /> 
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" /> 
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}" /> 
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}" /> 
    </application> 
  </compatibility> 
</assembly> 
```

to make them use Windows 10/11+ new segmented heap  
(compatibility is for running them outside the vista virtualization sandbox).  

I think it made RAM allocation a lot faster,  
it is noticeable especially in the large dataset.  

more testing is needed..  
<del>I've noticed `--verbose` is no longer present</del> edit: clear thanks.,  
<del>.. any idea for benchmarking tests?</del> edit: thanks.  

<hr/>

edit:  

well I've ran the bench for each data set,  
making sure to first use the patched binaries,  
to avoid false positive effect due to cache warming (not sure if it is "a thing" on my machine though..).  

and ..bad news :|

on 4 threads (8 total) it seems that only loading time for the large dataset improved (patched 33s, original 40s).  
encoding time got worst though, from 32s to 46s.
total time was patched:80s, original 72s.  

so I guess it isn't worth it (similar to Chrome, [1](https://techdows.com/2020/11/chrome-to-use-partitionalloc-instead-of-segment-heap-for-memory-savings.html),[2](https://techdows.com/2020/07/google-disables-windows-segment-heap-chrome-85-performance-issues.html) which now uses `PartitionAlloc` instead).  

closing..

**Comment by ggerganov** [comment]
The `--verbose` flag didn't do anything so I removed it.

For benchmarking, you can use the `bench` tool #89
