### ISSUE TITLE
Add large-v2 model

### ISSUE THREAD

**Issue by savchenko** [ggml-org/whisper.cpp#226]
In light of https://github.com/openai/whisper/commit/4179ed2475cc84cba66868b516232ef1b74dacdf, might be worth adding a new GGML.

**Comment by ggerganov** [comment]
It's already added: https://github.com/ggerganov/whisper.cpp/commit/9fe7306f4b16a974361b6a8bea370d6f5c3552f2

The old one is called `large-v1`. The new one is called just `large`. 
If you have already downloaded the old one, make sure to rename it to `large-v1` and download the new one.
